[package]
name = "hypre_rs"
version = "0.1.0"
links = "libhypre"
build = "build.rs"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpi = "0.6"

[build-dependencies]
bindgen = "0.60"
